title: Dauda Ayokunle Arowolo
logo: Logo 2.jpg
##description: An experienced Analyst skilled in working with diverse data sources and transforming complex datasets into actionable insights. I uncover trends and valuable insights that support informed decision‑making using Excel, SQL, Power BI, and advanced data manipulation. 
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
